### ISSUE TITLE
Subsampling using columns while using Regressor

### ISSUE THREAD

**Issue by subratsaxena** [GAA-UAM/GBNN#1]
Hi

I was trying to implement the GBNN Regressor using this library and I found out that while subsampling it in the fit function, it tries to create a new view by X_i = X[indices]. However, this should be done like this: X_i = X.iloc[indices]

![image](https://github.com/GAA-UAM/GBNN/assets/97718805/4da3b26d-e2c3-4a57-807b-d089f3890435)

Correct me if I am wrong.

**Comment by subratsaxena** [comment]
> Hi
> 
> I was trying to implement the GBNN Regressor using this library and I found out that while subsampling it in the fit function, it tries to create a new view by X_i = X[indices]. However, this should be done like this: X_i = X.iloc[indices]
> 
> ![image](https://user-images.githubusercontent.com/97718805/251699106-4da3b26d-e2c3-4a57-807b-d089f3890435.png)
> 
> Correct me if I am wrong.

In line 188 also, I needed to put .iloc to make it work

**Comment by samanemami** [comment]
The model takes the NumPy arrays.
Here you are passing Pandas data frame, which is the wrong input format.

Of course, you do not have to change the model by adding pandas methods, instead, you could [convert ](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.values.html)your input to a NumPy array.

Imagine X is Pandas Data frame, you could convert it as
```Python
X = X.values
```

Check your input, it should always be an array.

**Comment by samanemami** [comment]
The GBNN takes the NumPy array. 
Using Pandas Data Frame as the model input is not correct!
